version: '2'

services:

  app:
    build: .
    ports:
      - 12110:8080
    depends_on:
      - mongodb
      - mailhog

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=orderDB
    ports:
      - 27017:27017

  mongoui:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 12111:8081
    depends_on:
      - mongodb

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 12112:8025 # web ui