version: '3'

services:

  app:
    build: .
    ports:
      - 12110:8080
    depends_on:
      - mongodb
      - mailhog

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=orderDB
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/mongodb/data:/data/db

  mongoui:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 12111:8081
    depends_on:
      - mongodb
    entrypoint: [sh, -c, "sleep 5s && tini -- /docker-entrypoint.sh mongo-express"] # https://github.com/mongo-express/mongo-express-docker/issues/39#issuecomment-991798043

  mailhog:
    image: mailhog/mailhog
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 12112:8025 # web ui
    volumes:
      - ./docker-volumes/mailhog/data:/maildir