version: '2'

services:

  app:
    build: .
    ports:
      - 12110:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  mongoclient:
    image: mongoclient/mongoclient:latest
    depends_on:
      - mongodb
    ports:
      - 3000:3000

#    networks:
#      - spring-cloud-network

#networks:
#  spring-cloud-network:
#    driver: bridge