version: '2'

services:

  app:
    build: .
    ports:
      - 12110:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=order
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

#  mongoclient:
#    image: mongoclient/mongoclient:latest
#    depends_on:
#      - mongodb
#    environment:
#      - MONGO_SERVER=mongodb
#      #- MONGO_INITDB_DATABASE=order
##      - MONGO_INITDB_ROOT_USERNAME=admin
##      - MONGO_INITDB_ROOT_PASSWORD=admin
#    ports:
#      - 3000:3000


volumes:
  mongodata:
